# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i8MR158Xkc02tOzNU03cSO8HVrU9D8v4
"""





!pip install transformers sentence-transformers faiss-cpu gradio pypdf accelerate

import streamlit as st
from dotenv import load_dotenv
from langchain.schema import HumanMessage, AIMessage, SystemMessage
from langchain_ollama import ChatOllama, OllamaEmbeddings
from langchain.vectorstores import Chroma
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import PyPDFLoader
from langchain.chains import RetrievalQA
import os
import tempfile

# Load environment variables/API keys
load_dotenv()

def configure_page():
    st.set_page_config(
        page_title="StudyMate: PDF Chatbot",
        page_icon="📝",
        layout="wide",
        initial_sidebar_state="expanded",
    )
    st.title("📚 StudyMate - Chat with Your PDF")

def process_pdf(pdf_file):
    with tempfile.NamedTemporaryFile(delete=False, suffix='.pdf') as tmp_file:
        tmp_file.write(pdf_file.read())
        doc_path = tmp_file.name
    loader = PyPDFLoader(doc_path)
    documents = loader.load()
    splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
    docs = splitter.split_documents(documents)
    embeddings = OllamaEmbeddings(model="llama3")  # Or OpenAIEmbeddings if using OpenAI
    vectorstore = Chroma.from_documents(docs, embedding=embeddings)
    retriever = vectorstore.as_retriever()
    return retriever

def main():
    configure_page()
    if "messages" not in st.session_state:
        st.session_state.messages = [SystemMessage(content="You are a helpful AI assistant.")]

    uploaded_file = st.file_uploader("Upload your PDF", type="pdf")
    if uploaded_file:
        retriever = process_pdf(uploaded_file)
        chat_model = ChatOllama(model="llama3")  # Or chat_model = ChatOpenAI() for OpenAI
        qa_chain = RetrievalQA.from_chain_type(
            llm=chat_model,
            chain_type="stuff",
            retriever=retriever,
        )
        question = st.text_input("Ask something about your PDF:")
        if question:
            response = qa_chain.run(question)
            st.write(response)
            st.session_state.messages.append(HumanMessage(content=question))
            st.session_state.messages.append(AIMessage(content=response))

if __name__ == "__main__":
    main()